config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  root 'homes#top'

  devise_for :users, :controllers => {
    :registations => 'users/registations',
  }

  devise_for :admins
  resources :users, only: [:show, :edit, :update]
  resources :animes


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/anime.rb
class Anime < ApplicationRecord

  belongs_to :user
  attachment :image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :animes, dependent: :destroy

end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController

  def new
    @anime = Anime.new
  end

  def index
    @animes = Anime.all
  end

  def show
    @anime = Anime.find(params[:id])
  end

  def update
  end

  def edit
  end

  def create
    @anime = Anime.new(anime_params)
    @anime.user_id = current_user.id
    @anime.save
    redirect_to animes_path
  end

  def destroy
    @anime = Anime.find(params[:id])
    @anime.destroy
    redirect_to animes_path
  end

 private

 def anime_params
   params.require(:anime).permit(:anime_name, :introduction, :image)
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when User
    user_path(current_user)
    end
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:success] = "更新されました"
      redirect_to user_params
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/animes/index.html.erb
<h1>投稿一覧</h1>
 <%= render 'layouts/flash' %>

 <table class="table">
  <div class="text-right">
   <%= link_to new_anime_path, class: "btn btn-secondary text-right" do %>
   <i class="fas fa-plus-circle"></i>
   <% end %>
  </div>
   <thead>
     <tr>
       <th>投稿画像</th>
       <th>題名</th>
       <th>紹介</th>
       <th>投稿者</th>
     </tr>
   </thead>
   <tbody>
    <% @animes.each do |anime| %>
     <tr>
       <td>
        <% if anime.image == nil %>
         <%= image_tag ('no_image.png'), size: '45x45' %>
        <% else %>
         <%= attachment_image_tag anime, :image, size: '45x45' %>
        <% end %>
       </td>
       <td>
        <%= link_to anime_path(anime.id) do %>
        <%= anime.anime_name %>
        <% end %>
        </td>
       <td><%= anime.introduction %></td>
       <td><%= anime.user.name %></td>
     </tr>
   </tbody>
 </table>
 <% end %>

app/views/animes/new.html.erb
<h1>新規投稿</h1>
<%= form_with model: @anime, local:true do |f| %>
 <h4>画像</h4>
  <%= f.attachment_field :image %>
 <h4>題名</h4>
  <%= f.text_field :anime_name %>
 <h4>紹介</h4>
  <%= f.text_area :introduction %>

  <p><%= f.submit '投稿' %></p>
<% end %>

app/views/animes/show.html.erb
<h1>投稿詳細</h1>
  <table class="table">
    <thead>
     <tr>
      <th>画像</th>
      <th>題名</th>
      <th>紹介</th>
      <th>投稿者</th>
      <th></th>
     </tr>
    </thead>
    <tbody>
     <tr>
      <td>
        <% if @anime.image == nil %>
         <%= image_tag ('no_image.png'), size: '60x60' %>
        <% else %>
         <%= attachment_image_tag @anime, :image, size: '60x60' %>
        <% end %>
      </td>
      <td><%= @anime.anime_name %></td>
      <td><%= @anime.introduction %></td>
      <td><%= @anime.user.name %></td>
      <td>
       <% if @anime.user == current_user %>
        <%= link_to "削除", anime_path(@anime), method: :delete, data: {confirm: "削除しますか？"} %>
       <% end %>
      </td>
     </tr>
    </tbody>
  </table>

app/views/homes/about.html.erb
<h1>About</h1>

app/views/homes/top.html.erb
<h1>Hello</h1>

app/views/layouts/_flash.html.erb
<% flash.each do |color, message| %>
 <div class="alert alert-<%= color %>" role="alert"><%= message %>
  <button type="button" class="close" date-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
 </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <a class="navbar-brand p-3" href="/">home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navberDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </li>
          <li class="nav-item">
            <%= link_to "投稿一覧", animes_path %>
          </li>
          <li class="nav-item">
            <%= link_to "マイページ", user_path(current_user.id) %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AttendanceApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <%= yield %>
    </main>

  </body>
</html>

app/views/users/edit.html.erb
<h1>マイページ編集</h1>
 <%= form_with model:@user, local:true do |f| %>
  <label>名前</label>
  <%= f.text_field :name %>
  <label>画像</label>
  <%= f.attachment_field :profile_image %>

  <%= f.submit "保存" %>
 <% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>マイページ</h1>
<%= render 'layouts/flash' %>
 <table class="table">
  <thead>
   <tr>
     <th>画像</th>
     <td><% if current_user.profile_image == nil %>
          <%= image_tag ('no_image.png'), size: '120x120' %>
         <% else %>
          <%= attachment_image_tag current_user, :profile_image, size: '120x120' %>
         <% end %>
     </td>
   </tr>
   <tr>
     <th>名前</th>
     <td><%= current_user.name %></td>
   </tr>
  </thead>
  <tbody>
   <tr>
    <td></td>
    <td></td>
   </tr>
  </tbody>
 </table>
   <% if @user.id == current_user.id %>
   <p><%= link_to "編集", edit_user_path(@user) %></p>
   <% end %>